### PR TITLE
ENHANCEMENT: 'Apply' button for streamlining log filtering in debugging

### LINKED ISSUE #58: Add the apply filters button to the filter logs on click instead of processing every time after check/uncheck of the filter
**Describe the bug**
While debugging an bug report in this log viewer, I have to often check and uncheck filters from the different groups. The logs are often huge and it takes some time (approx 2 to 5 seconds) to process and apply on each change (check/uncheck) of the filter. 

**To Reproduce**
1. Load multiple filter groups
2. Open android bugreport
3. Check or uncheck different filters when all logs are loaded in the viewer
4. Check how long does it take to adjust the multiple filters

**Expected behavior**
All logs get filtered in a single process.

**Potential solution**
Add an "apply" button to filter all logs when the all changes (check/uncheck) of filtering is done.

### PR DESCRIPTION
**Pull request by MiteshVasoya**
[Problem]
Debugging with a bug report often requires checking and unchecking filters from different groups, resulting in long filter processing times, reducing productivity. The LogViewer currently lacks an explicit 'Apply' button to apply all changes at once. Users must select multiple filters or press space for their checking status to revert after each change.

[Solution]
- Implemented an 'Apply' button that applies all changes made to the filter and updates filtered logs.
- Added a user setting called ‘Apply filters on check’, allowing users to toggle whether filtering should occur on every check/uncheck of the filter. When disabled, users can use the 'Apply' button after changing their filters, updating the filtered logs. With it enabled, the current behavior is followed, like filtering logs for each change in the filter.

Closes #58

### CODE REVIEW

File: src/main/java/com/tibagni/logviewer/preferences/LogViewerPreferencesImpl.kt
Comment (tibagni) [inline src/main/java/com/tibagni/logviewer/preferences/LogViewerPreferencesImpl.kt:1]: Can we also add a couple test cases related to this new preference on "test/java/com/tibagni/logviewer/preferences/LogViewerPreferencesImplTests.kt"?

File: src/main/java/com/tibagni/logviewer/LogViewerView.kt [hunk 1]
```diff
@@ -956,10 +984,18 @@ class LogViewerViewImpl(private val mainView: MainView, initialLogFiles: Set<Fil
     moreFilterOptionsBtn = JButton()
     moreFilterOptionsBtn.toolTipText = "More options"
     moreFilterOptionsBtn.text = StringUtils.THREE_LINES
+    applyFiltersBtn = JButton()
+    applyFiltersBtn.actionCommand = "Apply"
+    applyFiltersBtn.text = "Apply"
+    applyFiltersBtn.toolTipText = "Apply all changes to the filters"
```
Comment (tibagni) [inline src/main/java/com/tibagni/logviewer/LogViewerView.kt:990]: Maybe "Apply all selected filters" is more intuitive?

**Review by tibagni — APPROVED** [review]
